### ISSUE TITLE
大佬你好，我按照你写的步骤，发现卡在创建数据库这里，好像是字符串出了问题？

### ISSUE THREAD

**Issue by TrueBoy** [AlphaBoom/notion_sync_umadb#1]
Run python main.py --local_properties "urarawin.properties" --generator "urarawin" \
Traceback (most recent call last):
start sync skill data...
  File "/home/runner/work/notion_sync_umadb/notion_sync_umadb/main.py", line 138, in <module>
    client.start_skill_data_sync(skill_database_title,root_page_id, thread_count=skill_sync_thread_count)
  File "/home/runner/work/notion_sync_umadb/notion_sync_umadb/src/sync_client.py", line 144, in start_skill_data_sync
    database_id = self._ensure_notion_database_exists(root_page_id, database_title, SyncType.skill)
  File "/home/runner/work/notion_sync_umadb/notion_sync_umadb/src/sync_client.py", line 66, in _ensure_notion_database_exists
    page_database = _create_database(type, title, parent_page_id)
  File "/home/runner/work/notion_sync_umadb/notion_sync_umadb/src/sync_client.py", line 23, in _create_database
    return SkillDatabasePage().createDatabase(database_name, parent_page_id)
  File "/home/runner/work/notion_sync_umadb/notion_sync_umadb/src/pages/skill_page.py", line 67, in createDatabase
    return createDatabase(self._generateCreateDatabaseRequest(database_name, parent_page_id))
  File "/home/runner/work/notion_sync_umadb/notion_sync_umadb/src/notion/notion_api.py", line 28, in createDatabase
    return Database.from_json(_post("databases", data=request.to_json()).text)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dataclasses_json/api.py", line 63, in from_json
    return cls.from_dict(kvs, infer_missing=infer_missing)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dataclasses_json/api.py", line 70, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dataclasses_json/core.py", line 2[19](https://github.com/TrueBoy/notion_sync_umadb/actions/runs/6157928100/job/16710363313#step:5:20), in _decode_dataclass
    init_kwargs[field.name] = _decode_generic(field_type,
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dataclasses_json/core.py", line 279, in _decode_generic
    vs = _decode_items(v_type, value.values(), infer_missing)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dataclasses_json/core.py", line 378, in _decode_items
    return list(_decode_item(type_args, x) for x in xs)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dataclasses_json/core.py", line 378, in <genexpr>
    return list(_decode_item(type_args, x) for x in xs)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dataclasses_json/core.py", line 371, in _decode_item
    return _decode_dataclass(type_arg, x, infer_missing)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dataclasses_json/core.py", line [21](https://github.com/TrueBoy/notion_sync_umadb/actions/runs/6157928100/job/16710363313#step:5:22)9, in _decode_dataclass
    init_kwargs[field.name] = _decode_generic(field_type,
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dataclasses_json/core.py", line 308, in _decode_generic
    res = _decode_dataclass(type_arg, value, infer_missing)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dataclasses_json/core.py", line 219, in _decode_dataclass
    init_kwargs[field.name] = _decode_generic(field_type,
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dataclasses_json/core.py", line 310, in _decode_generic
    res = _decode_generic(type_arg, value, infer_missing)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dataclasses_json/core.py", line 290, in _decode_generic
    xs = _decode_items(_get_type_arg_param(type_, 0), value, infer_missing)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dataclasses_json/core.py", line 378, in _decode_items
    return list(_decode_item(type_args, x) for x in xs)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dataclasses_json/core.py", line 378, in <genexpr>
    return list(_decode_item(type_args, x) for x in xs)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dataclasses_json/core.py", line 371, in _decode_item
    return _decode_dataclass(type_arg, x, infer_missing)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dataclasses_json/core.py", line 219, in _decode_dataclass
    init_kwargs[field.name] = _decode_generic(field_type,
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dataclasses_json/core.py", line 312, in _decode_generic
    res = _support_extended_types(type_arg, value)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/dataclasses_json/core.py", line [25](https://github.com/TrueBoy/notion_sync_umadb/actions/runs/6157928100/job/16710363313#step:5:26)0, in _support_extended_types
    else field_type(field_value))
ValueError: invalid literal for int() with base 10: '69eee59c-21ae-4962-a8c7-4f[35](https://github.com/TrueBoy/notion_sync_umadb/actions/runs/6157928100/job/16710363313#step:5:36)c7e6d2b3'
Error: Process completed with exit code 1.

**Comment by TrueBoy** [comment]
我的编程只会hello world，实在是看不懂怎么改QAQ

**Comment by AlphaBoom** [comment]
请问下是如何执行的脚本，看日志你期望的应该是执行[run_urara.py](run_urara.py)这个脚本。
```cmd
pipenv run python run_urara.py
```
另外适配新版本的时候有个bug我一直没提上来 a39c851，你也可以试试更新下是否解决（看提供的错误日志应该是无关的）

**Comment by TrueBoy** [comment]
> 请问下是如何执行的脚本，看日志你期望的应该是执行[run_urara.py](run_urara.py)这个脚本。
> 
> ```batchfile
> pipenv run python run_urara.py
> ```
> 
> 另外适配新版本的时候有个bug我一直没提上来 [a39c851](https://github.com/AlphaBoom/notion_sync_umadb/commit/a39c851bfb9a552d436ff5e1eef01e144f113697)，你也可以试试更新下是否解决（看提供的错误日志应该是无关的）

我就用你写的更新数据库的方法去创建的，fork你的项目后，填好api和root_key后点Github Action里面的`Create database use urarawin data `

更新：
奇怪了啊，我看你项目里面，你刚刚运行的workflow是正常的，我这边怎么就有问题了......

**Comment by AlphaBoom** [comment]
你的版本太老了，更新下版本，点Sync fork。
![image](https://github.com/AlphaBoom/notion_sync_umadb/assets/30779939/e6b7df3c-addb-478d-8c4a-a0eacd2a50cf)

**Comment by TrueBoy** [comment]
我更新了一下项目，现在又可以了，不好意思打扰了..........
